version: '3'

services:
    reviews: 
        build: ./
        depends_on: 
            - 'database'
        ports: 
            - '3003:3003'
        command: bash -c './wait-for-it.sh database:3306 && npm run seed && npm start'
        
    database:
        image: mysql:5.7.18
        environment: 
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "user"
            MYSQL_DATABASE: "yelpreviews"
        ports:
            - "3306:3306"
        volumes:
            - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
            
            
